### ISSUE TITLE
Uploading a PNG thumbnail for a book creates a black region around thumbnail

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapii-web-client#10]
Refer First image in attached screenshot:

**Steps to reproduce:**
1. While uploading a Book, choose a PNG thumbnail for the book.
2. The Book should have some transparent areas within the image
3. After book  thumbnail upload is complete, logout and go to home screen. The Image now looks modified with black regions in place of transparent areas.

![image](https://user-images.githubusercontent.com/45028441/52125740-6e871b80-2653-11e9-9ada-c9825a7efb67.png)

**Comment by damooo** [comment]
Anna,
as we are using iiif url for thumbnails, we can request in any format anna. presently, '.jpg' format is hard coded in web client's thumbnail uri generator function.
here is code link: https://github.com/vedavaapi/vedavaapii-web-client/blob/812e516cd7bf62efd7a0c1b1fc619209c5e37509/src/app/ui/home/home.component.ts#L69

i.e presently it requests https://api.vedavaapi.org/py/demo/iiif_image/v1/objstore/5c528e5842b93b4c115ec9ee/full/100,150/0/default.jpg url for that image, wherein jpg doesn't support transperancy. as we have choice we can request instead png format https://api.vedavaapi.org/py/demo/iiif_image/v1/objstore/5c528e5842b93b4c115ec9ee/full/100,150/0/default.png

**Comment by damooo** [comment]
And anna, instead of using dimensions '/100,150/', we can just use '/,150/' to just restrict height iof thumbnail if we want. this will preserve aspect ratio, while keeping height in required limits. otherwise images looks distorted, because of change in aspect ratio. we can see second image thumbnail in above screenshot.

**Comment by shashikiranraifox** [comment]
> And anna, instead of using dimensions '/100,150/', we can just use '/,150/' to just restrict height iof thumbnail if we want. this will preserve aspect ratio, while keeping height in required limits. otherwise images looks distorted, because of change in aspect ratio. we can see second image thumbnail in above screenshot.

A Separate Issue will be opened for distortion of Aspect ratio. [Ideally it is better to restrict the thumbnail aspect ratio while upload itself]

This issue is only for the black region around thumbnail. Will close the issue after fixing it.

**Comment by shashikiranraifox** [comment]
Issue fixed.
