### ISSUE TITLE
Unique url&web-page for a book

### ISSUE THREAD

**Issue by damooo** [vedavaapi/vedavaapii-web-client#11]
presently, there is no view/web-page for a book.
we should be able to represent of a book by it's own url like `https://apps.vedavaapi.org/client/books/book_id`, etc. which should show all book details there, like book name, thumbnail, author, description, any further fields that may be added, in ui in that page.
and there may be a button to `view in mirador`, and to download iiif manifest, etc.

and in books list in `All Books`, or at welcome page, when we click on a book icon, we should be redirected to that book's ui page, from where user can choose to view in mirador if he want by above button, or just view details of that book.

**Comment by shashikiranraifox** [comment]
Fixed in #16
