### ISSUE TITLE
Vedavaapii Backend server is sending 503 Server Unavailable response for Login and fetching Books API calls.

### ISSUE THREAD

**Issue by gdkirankumar** [vedavaapi/vedavaapii-web-client#20]
Start the Vedavaapii Web Client Application.
Open the Home Page. 

Expected Result: The Home Page should show the Books in the Carousel
Actual result: The Home page does not show any books. The Debug console we can see that the Server is sending 503 Response.

Similarly If we try to login, we get the same 503 Error Response from Server.
The Server URL we use is: https://apps.vedavaapi.org/dev/api.

![Screenshot (63)](https://user-images.githubusercontent.com/46882944/55701679-ba5a9600-59f1-11e9-94a5-42eec6bf832f.png)

**Comment by damooo** [comment]
now available.
