### ISSUE TITLE
configurable api endpoints, etc

### ISSUE THREAD

**Issue by damooo** [vedavaapi/vedavaapii-web-client#5]
Anna,
presently constants like api url, mirador app url, etc are factored out into endpoints.service.ts. And when we build it, we get dist/ to deploy, where all those ts files are compiled and uglified. we cannot point to different service from it. even if we can edit _code_, and build, that process cannot be automated, as we have to edit 'code' and then build.

So can we load these constants from a json file, say assets/config/endpoints.json. so that we can just dynamically generate config json, and keep it at that place. thus after build also uglified version still gets initial config from configurable file there., and we can automate it's generation.

here are relevant so qns.
https://stackoverflow.com/questions/27720568/how-is-possible-to-load-some-setting-from-json-file-before-angular-app-starts
https://stackoverflow.com/questions/42110817/load-config-json-file-in-angular-2
http://plnkr.co/edit/VmSJiS6zzNp95UZ9Z7zm?p=preview

**Comment by damooo** [comment]
that is not of production one anna,
we doesn't serve through ng serve, which is basically intended for testing, and live reloading at the time of develpment.
in production serving, we serve only build result /dist. which we get after ng build. there, there will not be any ts files, or other.

and as @sai-r-susarla anna asked me in a discussion, we should be able to generate configuration files from other admin deployment panel, which generates config file, and deploy client on any institution's server.

**Comment by shashikiranraifox** [comment]
Closing this Issue as We have now moved to a different scheme[of using a pop-up to collect the server URL]
