### ISSUE TITLE
configurable mirador integration

### ISSUE THREAD

**Issue by damooo** [vedavaapi/vedavaapii-web-client#6]
Anna,
presently, we just integrate external html file into our page. all things like what collection to view, or what manifest to view, what is api url to use etc, cannot be controlled from main app. those collection uri, manifest uri, api uri are hard coded in other project.

We will now on wards have multiple collections, instead of previous 'books.json' default collection. so we should have control over which collection to be loaded into mirador etc. we can pass these details in query params of external mirador page url, and then mirador will be instantiated with those configs.

And in dashboard we should have list of collections displayed, and able to choose one and load that collection in below mirador app dynamically. to get list of collections, we can just do get resources call with jsonClass having 'Library' value.

**Comment by shashikiranraifox** [comment]
The issue is no longer relevant as Liraries(collections) will be rendered by the Vedavaapi Web Application itself. As per new Wireframes, Users can view Libraries and also view books in a Library. Each book can then be viewed in a Mirador based view.
