### ISSUE TITLE
updating book/page/ etc.

### ISSUE THREAD

**Issue by damooo** [vedavaapi/vedavaapii-web-client#8]
presently we have ui to create a book with meta, and thumbnail, etc.
there should be way to update book's info, thumbnail, or to swap page image, etc.

we can even use existing ui, but give option to select a book id, and update it, as api endpoint and json structure is same for both purposes.

**Comment by shashikiranraifox** [comment]
Yes, we have this feature in mind. This feature shall be taken up in next sprint/week

**Comment by shashikiranraifox** [comment]
Feature to update book details has been implemented. 
Option to replace a book page will be taken up in a different story.
